/*
	Name: 4th_Reich
	Author: Yettie
	Date: 25/04/17
	Description: CfgPatches.hpp
*/
"Reich_Commander",
"Reich_Commander_w",
"Reich_Commander_S",
"Reich_Grenadier",
"Reich_Grenadier_w",
"Reich_Grenadier_S",
"Reich_Gunner",
"Reich_Gunner_w",
"Reich_Gunner_S",
"Reich_AT_Rifleman",
"Reich_AT_Rifleman_w",
"Reich_AT_Rifleman_S",
"Reich_Heavy_MG",
"Reich_Heavy_MG_w",
"Reich_Heavy_MG_S",
"Reich_MM",
"Reich_MM_w",
"Reich_MM_S",
"Reich_Crew_Black",
"Reich_Commander_Black",
"SS_Commander",
"SS_Trooper_MG",
"SS_Trooper_EXP",
"SS_Trooper_MM",
"SS_Trooper_BR",
"SS_Trooper_RM",
"SS_Officer",
"Reich_Shock_trp",
"Reich_Shock_trp_leader",
"Reich_Shock_trp_aa",
"Reich_Shock_trp_at",
"the_fourth_reich_AT_team",
"the_fourth_reich_AA_team",
"SS_Commander",
"Reich_Pilot",
"SS_Trooper_GD",
"the_fourth_reich_FT",
"the_fourth_reich_FT2",
"the_fourth_reich_FT3",
"the_fourth_reich_FT2_1",
"the_fourth_reich_FT2_2",
"the_fourth_reich_FT3_1",
"the_fourth_reich_FT3_2",
"the_fourth_reich_FT_2",
"the_fourth_reich_FT_1",

"Nazi_Bo105_Armed",
"Nazi_Bo105_rpm",
"Nazi_Fighter",
"Nazi_Gunship",
"Nazi_VTOL_Transport",
"Nazi_VTOL_Transport2",

"Nazi_MBT_Kuma",
"Nazi_AAA",
"SS_Blitz",
"SS_Blitz_HMG",
"Nazi_AA_Truck1",
"Nazi_AA_Truck2",
"Nazi_Transport",
"Nazi_Swift_attack",
"Nazi_Swift_attack_armed",
"Nazi_LAV",
"Nazi_SAM",
"Nazi_SAA",
"Nazi_GBAD",
"Nazi_HMG_high",
"Nazi_Mortar",

