
"PMC_Commander_D",
"PMC_Grenadier_D",
"PMC_Gunner_D",
"PMC_AT_Rifleman_D",
"PMC_Heavy_MG_D",
"PMC_MM_D",
"PMC_Soldier_D",
"PMC_Soldier2_D",
"PMC_Soldier3_D",
"PMC_Sniper_D",
"PMC_Pilot_D",
"PMC_SQD_D",

"PMC_Commander_W",
"PMC_Grenadier_W",
"PMC_Gunner_W",
"PMC_AT_Rifleman_W",
"PMC_Heavy_MG_W",
"PMC_MM_W",
"PMC_Soldier_W",
"PMC_Soldier2_W",
"PMC_Soldier3_W",
"PMC_Sniper_W",
"PMC_Pilot_W",


"PMC_Team_D",
"PMC_SQD_D",
"PMC_Team_W",
"PMC_SQD_W",

"PMC_Jeep",
"PMC_little_bird",
"PMC_Boat_Transport",
"PMC_Hatchback",
"PMC_Scooter",