wboard = _this select 0;
SOR_SLIDESHOW = 0;
SOR_ACT = 0;
SOR_BHT = 0;
SOR_BFWT = 0;
SOR_BPJOT = 0;
SOR_AHCT = 0;
SOR_BFWCT = 0;
SOR_AFWCT = 0;

// Basic Parachute Jump Ops Powerpoint
wboard addAction [("<t color='#16e616'>" + ("Tags - Basic Parachute Jump Ops") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide1.jpg']];SOR_BPJOT = 1;SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_SLIDESHOW == 0)) && (player isKindOf 'SOR_AirCommand_D')"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide2") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide2.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 1))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide3") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide3.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 2))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide4") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide4.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 3))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide5") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide5.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 4))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide6") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide6.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 5))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide7") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide7.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 6))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide8") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide8.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 7))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide9") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide9.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 8))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide10") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide10.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 9))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide11") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\parachute_ops\Slide11.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BPJOT > 0) && (SOR_SLIDESHOW == 10))"];

// Aircrew Training Powerpoint
wboard addAction [("<t color='#16e616'>" + ("Tags - Aircrew Training") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide1.jpg']];SOR_ACT = 1;SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_SLIDESHOW == 0)) && (player isKindOf 'SOR_AirCommand_D')"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide2") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide2.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 1))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide3") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide3.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 2))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide4") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide4.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 3))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide5") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide5.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 4))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide6") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide6.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 5))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide7") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide7.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 6))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide8") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide8.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 7))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide9") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide9.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 8))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide10") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide10.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 9))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide11") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide11.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 10))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide12") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide12.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 11))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide13") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide13.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 12))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide14") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide14.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 13))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide15") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide15.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 14))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide16") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide16.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 15))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide17") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide17.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 16))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide18") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide18.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 17))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide19") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide19.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 18))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide20") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide20.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 19))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide21") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\aircrew_training\Slide21.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_ACT > 0) && (SOR_SLIDESHOW == 20))"];

// Basic Heli Transport Powerpoint
wboard addAction [("<t color='#16e616'>" + ("Tier E2 - Basic Helicopter Transport Training (B.H.T.T)") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide1.jpg']];SOR_BHT = 1;SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_SLIDESHOW == 0)) && (player isKindOf 'SOR_AirCommand_D')"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide2") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide2.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 1))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide3") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide3.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 2))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide4") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide4.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 3))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide5") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide5.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 4))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide6") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide6.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 5))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide7") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide7.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 6))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide8") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide8.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 7))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide9") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide9.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 8))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide10") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide10.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 9))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide11") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide11.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 10))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide12") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide12.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 11))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide13") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide13.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 12))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide14") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide14.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 13))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide15") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide15.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 14))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide16") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide16.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 15))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide17") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide17.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 16))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide18") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide18.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 17))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide19") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide19.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 18))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide20") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide20.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 19))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide21") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide21.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 20))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide22") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide22.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 21))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide23") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide23.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 22))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide24") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\heli_transport\Slide24.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BHT > 0) && (SOR_SLIDESHOW == 23))"];

// Basic Fixed Wing Transport Powerpoint
wboard addAction [("<t color='#16e616'>" + ("Tier E2 - Basic Fixed Wing / Gunship Co-Pilot Training (B.F.G.C.T)") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide1.jpg']];SOR_BFWT = 1;SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_SLIDESHOW == 0)) && (player isKindOf 'SOR_AirCommand_D')"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide2") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide2.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 1))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide3") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide3.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 2))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide4") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide4.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 3))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide5") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide5.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 4))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide6") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide6.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 5))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide7") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide7.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 6))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide8") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide8.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 7))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide9") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide9.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 8))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide10") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide10.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 9))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide11") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide11.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 10))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide12") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide12.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 11))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide13") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide13.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 12))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide14") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide14.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 13))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide15") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide15.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 14))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide16") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide16.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 15))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide17") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide17.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 16))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide18") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide18.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 17))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide19") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide19.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 18))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide20") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide20.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 19))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide21") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide21.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 20))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide22") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide22.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 21))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide23") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide23.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 22))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide24") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide24.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 23))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide25") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide25.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 24))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide26") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\basic_fixed_wing\Slide26.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_BFWT > 0) && (SOR_SLIDESHOW == 25))"];

// Advanced Heli CAS Training Powerpoint
wboard addAction [("<t color='#16e616'>" + ("Tier E3 - Advanced Helicopter CAS Training (A.H.C.T)") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide1.jpg']];SOR_AHCT = 1;SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_SLIDESHOW == 0)) && (player isKindOf 'SOR_AirCommand_D')"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide2") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide2.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 1))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide3") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide3.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 2))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide4") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide4.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 3))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide5") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide5.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 4))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide6") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide6.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 5))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide7") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide7.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 6))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide8") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide8.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 7))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide9") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide9.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 8))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide10") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide10.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 9))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide11") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide11.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 10))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide12") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide12.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 11))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide13") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide13.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 12))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide14") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide14.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 13))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide15") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide15.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 14))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide16") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_heli_cas\Slide16.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AHCT > 0) && (SOR_SLIDESHOW == 15))"];

// Advanced Fixed Wing CAS Training Powerpoint
wboard addAction [("<t color='#16e616'>" + ("Tier E4 - Advanced Fixed Wing CAS Training (A.F.C.T)") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide1.jpg']];SOR_AFWCT = 1;SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_SLIDESHOW == 0)) && (player isKindOf 'SOR_AirCommand_D')"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide2") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide2.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 1))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide3") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide3.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 2))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide4") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide4.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 3))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide5") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide5.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 4))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide6") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide6.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 5))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide7") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide7.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 6))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide8") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide8.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 7))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide9") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide9.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 8))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide10") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide10.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 9))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide11") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide11.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 10))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide12") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide12.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 11))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide13") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide13.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 12))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide14") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide14.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 13))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide15") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide15.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 14))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide16") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide16.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 15))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide17") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide17.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 16))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide18") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide18.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 17))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide19") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide19.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 18))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide20") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide20.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 19))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide21") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide21.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 20))"];
wboard addAction [("<t color='#16e616'>" + ("Next Slide22") + "</t>"),"[wboard setObjectTextureGlobal [0, '160thSOR_Data\air\adv_fixedwing_cas\Slide22.jpg']];SOR_SLIDESHOW = SOR_SLIDESHOW + 1; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_AFWCT > 0) && (SOR_SLIDESHOW == 21))"];

// Utility Controls
wboard addAction [("<t color='#FFA700'>" + ("Previous Slide") + "</t>"),"SOR_SLIDESHOW = SOR_SLIDESHOW - 2; ","",1,true,true,"","((_target distance _this) < 5 && (SOR_SLIDESHOW > 1))"];
wboard addAction [("<t color='#FF0000'>" + ("End Powerpoint") + "</t>"),"[wboard setObjectTextureGlobal [0, '#(argb,8,8,3)color(0,0,0,0.0,co)']];SOR_SLIDESHOW = -1;SOR_ACT = 0;SOR_BHT = 0;SOR_BFWT = 0;SOR_BPJOT = 0;SOR_AHCT = 0;SOR_BFWCT = 0;SOR_AFWCT = 0; removeAllActions wboard;","",1,true,true,"","((_target distance _this) < 5 && (SOR_SLIDESHOW > 0))"];